### ISSUE TITLE
fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [ocramz/rigel-viz#1]
```
rigel-viz                      > /tmp/stack-8763d6d98e0d5a78/rigel-viz-0.2.0.0/src/RigelViz.hs:177:24: error:
rigel-viz                      >     • Couldn't match expected type ‘A.Key’ with actual type ‘T.Text’
rigel-viz                      >     • In the first argument of ‘(.=)’, namely ‘showPos p’
rigel-viz                      >       In the first argument of ‘(:)’, namely ‘(showPos p .= emd)’
rigel-viz                      >       In the expression: (showPos p .= emd) : acc
rigel-viz                      >     |
rigel-viz                      > 177 |       EsPos p emd  -> (showPos p .= emd) : acc
rigel-viz                      >     |                        ^^^^^^^^^
```

**Comment by ocramz** [comment]
Thanks @juhp , I believe this is related to the recent security patch in aeson.
